name: app_akademie_exercises
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  blobs: ^2.0.0
  card_swiper: ^3.0.1
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  image_picker: ^1.0.2
  logger: ^2.0.2
  lottie: ^2.6.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0




flutter:

  
  uses-material-design: true

  assets:
    - assets/images/capetown.jpg
    - assets/images/OZm.gif
    - assets/images/Vho.gif
    - assets/images/6oa.gif
    - assets/images/1np8.gif
    - assets/images/14Lo.gif
    - assets/images/harry1.jpeg
    - assets/images/harry2.jpeg
    - assets/images/harry3.jpeg
    - assets/images/Frame-1.json

  

  

  

  
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather-BlackItalic.ttf
          style: italic

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic

    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic


 
 
